# Generated by Django 2.2.6 on 2021-02-14 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_auto_20210205_0624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': (('setar_nfe', 'Usuário pode alterar parametro NF-e'), ('show_dashboard', 'Pode visualizar o dashboard'), ('permissao3', 'Permissão 3'))},
        ),
    ]
