# Generated by Django 2.2.6 on 2021-03-16 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_auto_20210214_0348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemdopedido',
            options={'verbose_name': 'Item do Pedido', 'verbose_name_plural': 'Itens do Pedido'},
        ),
    ]
