# Generated by Django 2.2.6 on 2021-03-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_tabelaexistente'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('first_name', 'telefone')},
        ),
    ]
